add_executable(convert_example_LHEF.exe convert_example_LHEF.cc)
target_link_libraries(convert_example_LHEF.exe PRIVATE HepMC3::HepMC3 HepMC3::hdf5IO HDF5::HDF5)
find_package(ZLIB)
if(ZLIB_FOUND)
  target_link_libraries(convert_example_LHEF.exe PRIVATE ZLIB::ZLIB)
  target_compile_definitions(convert_example_LHEF.exe PRIVATE HEPMC3_USE_COMPRESSION HEPMC3_Z_SUPPORT=1)
endif()
if(${CMAKE_VERSION} VERSION_GREATER "3.14")
  find_package(LibLZMA)
endif()
if(LIBLZMA_FOUND)
  target_link_libraries(convert_example_LHEF.exe PRIVATE LibLZMA::LibLZMA)
  target_compile_definitions(convert_example_LHEF.exe PRIVATE HEPMC3_USE_COMPRESSION HEPMC3_LZMA_SUPPORT=1)
endif()
find_package(BZip2)
if(BZIP2_FOUND)
  target_link_libraries(convert_example_LHEF.exe PRIVATE BZip2::BZip2)
  target_compile_definitions(convert_example_LHEF.exe PRIVATE HEPMC3_USE_COMPRESSION HEPMC3_BZ2_SUPPORT=1)
endif()
find_package(zstd 1.4.0)
if(zstd_FOUND)
  target_link_libraries(convert_example_LHEF.exe PRIVATE zstd::libzstd_shared)
  target_compile_definitions(convert_example_LHEF.exe PRIVATE HEPMC3_USE_COMPRESSION HEPMC3_ZSTD_SUPPORT=1)
endif()
set_target_properties(convert_example_LHEF.exe PROPERTIES
  RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/outputs/${CMAKE_INSTALL_BINDIR}/$<0:>)

if (USE_INSTALLED_HEPMC3)
  install(TARGETS convert_example_LHEF.exe DESTINATION ${CMAKE_INSTALL_BINDIR})
endif()